### ISSUE TITLE
Cannot unlock season 1 funds when claimed rewards before

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/hopr-stake#42]
When a user has claimed rewards before, the unlock produces an error and doesn't complete. The UI doesn't show any indication of an error occuring.

**Comment by nionis** [comment]
Currently, we have disabled `claim` and `sync` to minimize the issue.

**Comment by tolbrino** [comment]
Ref https://github.com/hoprnet/hopr-devrel/pull/158

**Comment by QYuQianchen** [comment]
On the [SC level](https://blockscout.com/xdai/mainnet/address/0x912F4d6607160256787a2AD40dA098Ac2aFE57AC/contracts), when calling `unlock`, it first `_sync` (L. 1223) the account stake/reward and then `_claim` (L.1227) the reward, before transferring back the staked `xHOPR` token and `HoprBoost` NFTs.

`_claim` forbids accounts with `0` increment in rewards (L.1319) to be further executed. This creates issue when a staker manually calls `claim()` after `PROGRAM_END` (`1642424400`). If a staker did call `claim()` after  `PROGRAM_END` and before calling `unlock()`, it's not possible to release their stake, or NFT.

Luckily, NFTs can be recovered through `reclaimErc721Tokens()`.

**Comment by SCBuergel** [comment]
A [PR for this issue](https://github.com/hoprnet/hopr-stake/pull/43) is pending. Next steps are

1. [ ] Review from at least @robertkiel & @tolbrino 
2. [ ] Identify user with small amount of locked tokens for testing purposes --> Initiated via TG
3. [ ] deploy contract, carry out MS transactions as outlined in the [Checklist in HoprWhithat.sol](https://github.com/hoprnet/hopr-stake/pull/43/files#diff-99274accf35398986cae56b9336e575994a18d3f3018e332981d3f396c6c49e6R12-R24) --> TODO @QYuQianchen to support that process with the signers
4. [ ] Test the process with two users bilaterally --> TODO Sebastian or Andrius
5. [ ] Identify further tasks for unlocking everyone, even without going through the whitehat process once >= 90% of the funds are recovered --> TODO @QYuQianchen

**Comment by tolbrino** [comment]
Since the rewards were drained nobody can run into the situation anymore. Further steps are handled in #46 . Thus I am closing this issue.
